"""add excluded_words table

Revision ID: 51e0075e25f5
Revises: 8c39c6f5ae56
Create Date: 2026-08-09 00:10:14.373156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e0075e25f5'
down_revision: Union[str, Sequence[str], None] = '8c39c6f5ae56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excluded_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english_key', sa.String(length=255), nullable=False),
    sa.Column('russian_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excluded_words_english_key'), 'excluded_words', ['english_key'], unique=False)
    op.create_index(op.f('ix_excluded_words_russian_key'), 'excluded_words', ['russian_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excluded_words_russian_key'), table_name='excluded_words')
    op.drop_index(op.f('ix_excluded_words_english_key'), table_name='excluded_words')
    op.drop_table('excluded_words')
    # ### end Alembic commands ###
