"""initial schema

Revision ID: 8c39c6f5ae56
Revises: 
Create Date: 2026-08-07 23:12:03.538101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c39c6f5ae56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(length=255), nullable=False),
    sa.Column('russian', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_english'), 'words', ['english'], unique=False)
    op.create_index(op.f('ix_words_russian'), 'words', ['russian'], unique=False)
    op.create_index(op.f('ix_words_topic'), 'words', ['topic'], unique=False)
    op.create_table('answer_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('judged_by', sa.String(length=20), nullable=True),
    sa.Column('claude_explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pending_word_id', sa.Integer(), nullable=True),
    sa.Column('pending_direction', sa.String(length=10), nullable=True),
    sa.Column('pending_asked_at', sa.DateTime(), nullable=True),
    sa.Column('pending_import_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pending_word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('correct_count_in_cycle', sa.Integer(), nullable=False),
    sa.Column('cycle_start_at', sa.DateTime(), nullable=True),
    sa.Column('last_asked_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('learned_at', sa.DateTime(), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=False),
    sa.Column('total_wrong', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', name='uq_learning_progress_word_id')
    )
    op.create_index(op.f('ix_learning_progress_next_review_at'), 'learning_progress', ['next_review_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_progress_next_review_at'), table_name='learning_progress')
    op.drop_table('learning_progress')
    op.drop_table('bot_state')
    op.drop_table('answer_log')
    op.drop_index(op.f('ix_words_topic'), table_name='words')
    op.drop_index(op.f('ix_words_russian'), table_name='words')
    op.drop_index(op.f('ix_words_english'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
