"""add session_remaining to bot_state

Revision ID: b854c7ac4251
Revises: 51e0075e25f5
Create Date: 2026-08-10 19:08:30.065807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b854c7ac4251'
down_revision: Union[str, Sequence[str], None] = '51e0075e25f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bot_state',
        sa.Column('session_remaining', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_state', 'session_remaining')
    # ### end Alembic commands ###
